version: "3"

services:
  app:
    image: node:alpine
    tty: true
    volumes:
      - ./src:/src
    working_dir: "/src/my-app"
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: npm start
